apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "project.fullname" . }}-celery
  labels:
    {{- include "project.labels" . | nindent 4 }}-celery
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "project.selectorLabels" . | nindent 6 }}-celery
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "project.selectorLabels" . | nindent 8 }}-celery
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "project.fullname" . }}-celery
          image: "{{ .Values.image.app }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.envFrom.name }}
          command:
            - some celery command
        {{- with .Values.resources_celery }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
